INICIO 	EQU 100
FIM	EQU 103
SOMA	EQU 241
CONT 	EQU 242
MEDIA 	EQU 240
	MOV A,0;
	MOV [CONT],A;
	MOV [MEDIA],A;
	MOV A,[INICIO];
	MOV [SOMA],A;
	MOV A,INICIO;
	MOV B,A;
LACO_S	MOV A,[SOMA];
	INC B;
	ADD A,[B];
	MOV [SOMA],A;
	MOV A,[CONT];
	INC A;
	MOV [CONT],A;
	MOV A,B;
	CMP A,FIM;
	JBE LACO_S;
LACO_M	MOV A,[SOMA];
	SUB A,[CONT];
	JC ACABA;
	MOV [SOMA],A;
	MOV A,[MEDIA];
	INC A;
	MOV [MEDIA],A;
	JMP LACO_M;
ACABA	HLT;
